### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by masudr4n4** [franpog859/NAP#1]
Hallo @franpog859 
I am a graphic designer want to make a logo for this projects if you have any requirements then let me know its free for open source projects
Thank you

**Comment by franpog859** [comment]
Sure, @maaudrana ! You are lucky because I wanted to grab my graphic tablet today and try it by myself :D 
I want to keep it similar to NASA logo but with NAP sign instead. I found that it could be the BAMBI font.
I also need the background fullscreen image and the "cancel" and "stop" buttons in the same style. 
Put it in some lowercase named folder like "graphic" or so. 
Thanks!

**Comment by masudr4n4** [comment]
Hi sir here is my logo. if you need any change please comment.

![nap-01](https://user-images.githubusercontent.com/34313493/42055919-76809f10-7b3a-11e8-99d7-63496e808c00.jpg)

**Comment by franpog859** [comment]
I think it's great! I like it.
Do you consider making the background image and buttons in the same style? Also minimalist, NASA like colors, maybe some little stars in the background. Buttons somehow need to stick out from the background.

**Comment by masudr4n4** [comment]
![nap3-01](https://user-images.githubusercontent.com/34313493/42133104-f8f36f4c-7d45-11e8-8510-538bc223e40f.jpg)

**Comment by franpog859** [comment]
I think the first logo was great. We will stick to it ;)
Previously I was asking about the app background image. If you consider to make it, obviously! It could be also minimalist, as the first logo is. Buttons can be round and blue with red border to harmonize with the logo and to stick out from the background. 
Thanks!

**Comment by franpog859** [comment]
Hey, @maaudrana ! If you've done something cool feel free to open a pull request 😄 I will be able to comment it in more accessible way and hopefully to merge it some day.
